### ISSUE TITLE
[CSSBattle] Daily Target - Jun 7, 2025

### ISSUE THREAD

**Issue by dcotelessa** [dcotelessa/cssbattle-solutions#10]
### Date

Jun 7, 2025

### CSS Solution(s)

```css
<p a><p a><p><style>*{border:var(--b,0)solid;body{background:#5AA4B7;margin:70 120;--b:5vw;-webkit-box-reflect:left -40vw}[a]{box-shadow:-15vw -70px,15vw 70px}p{position:fixed;border-radius:1in;--b:10px;margin:50 20;width:60;+p{rotate:90deg;+p{rotate:45deg
```

### Comparison Images

<img width="852" alt="Image" src="https://github.com/user-attachments/assets/5f77a03d-72c3-49bc-98af-7a68b8e2fcef" />

### Additional Notes (Optional)

Boxed asterisk.*

### Confirmation

- [x] I have tested my CSS solution
- [x] The comparison images show the target vs my result
