### ISSUE TITLE
[CSSBattle] Daily Target - Jun 8, 2025

### ISSUE THREAD

**Issue by dcotelessa** [dcotelessa/cssbattle-solutions#13]
### Date

Jun 8, 2025

### CSS Solution(s)

```css
<p><style>p{padding:20;margin:60-110;scale:1 .5}*{background:radial-gradient(1q,#F2EAA8 4vw,var(--c,#EE7667)0 106q,#F2EAA8);*{--c:;margin:10%42.5%;border:5vw solid#F2EAA8
```

### Comparison Images

<img width="860" alt="Image" src="https://github.com/user-attachments/assets/765a9fb3-4602-4469-9b6c-a03a21eb5b5a" />

### Additional Notes (Optional)

Orange coin.

### Confirmation

- [x] I have tested my CSS solution
- [x] The comparison images show the target vs my result
