### ISSUE TITLE
[CSSBattle] Daily Target - Jun 10, 2025

### ISSUE THREAD

**Issue by dcotelessa** [dcotelessa/cssbattle-solutions#29]
### Date

Jun 10, 2025

### CSS Solution(s)

```css
<p><style>*{p{margin:-140 0}background:#EEB850;border:solid#243D83;border-width:20 20 0;margin:110 50;*{margin:40 20 0;height:60
```

### Comparison Images

<img width="858" alt="Image" src="https://github.com/user-attachments/assets/e1dd61bc-af53-48f4-a521-e99ae5a87e93" />

### Additional Notes (Optional)

Building...

### Confirmation

- [x] I have tested my CSS solution and it renders correctly
- [x] My CSS code blocks are properly formatted with opening and closing backticks
- [x] The comparison images (if any) clearly show the target vs my result
