### ISSUE TITLE
[CSSBattle] Daily Target - Jun 13, 2025

### ISSUE THREAD

**Issue by dcotelessa** [dcotelessa/cssbattle-solutions#32]
### Date

Jun 13, 2025

### CSS Solution(s)

```css
<p><img><p><img><style>*{background:var(--b,#EBF6F0);p{+p{scale:-1;margin:0-3}img{--b:#D95362;padding:65;margin:12-3}width:387;height:142;margin:0;--b:radial-gradient(1q at 257px 100%,#0000 5em,#D95362 0 130px,#0000
```

### Comparison Images

<img width="856" alt="Image" src="https://github.com/user-attachments/assets/d550bb32-5a64-4cf4-948f-a5d7a2f213ca" />

### Additional Notes (Optional)

Symmetry.

### Confirmation

- [x] I have tested my CSS solution and it renders correctly
- [x] My CSS code blocks are properly formatted with opening and closing backticks
- [x] The comparison images (if any) clearly show the target vs my result
