### ISSUE TITLE
[CSSBattle] Daily Target - Jun 14, 2025

### ISSUE THREAD

**Issue by dcotelessa** [dcotelessa/cssbattle-solutions#33]
### Date

Jun 14, 2025

### CSS Solution(s)

```css
<p><p><p><style>*{background:#6592CF;border:solid#F7CB71;border-width:0 0 20 20;margin:var(--m,60 90);+*,p,p+p+p{scale:-1}*+*{--m:0 0 0 20}p{position:fixed;--m:20 0 0 20;width:120;height:100}p+p{scale:1;--m:40 0 0 20;width:80;height:60;+p{--m:60;width:40;height:20
```

### Comparison Images

<img width="858" alt="Image" src="https://github.com/user-attachments/assets/44a27d51-be45-4e9f-b438-9dc9e98be1f4" />

### Additional Notes (Optional)

Maze.

### Confirmation

- [x] I have tested my CSS solution and it renders correctly
- [x] My CSS code blocks are properly formatted with opening and closing backticks
- [x] The comparison images (if any) clearly show the target vs my result
