### ISSUE TITLE
[CSSBattle] Daily Target - Jun 18, 2025

### ISSUE THREAD

**Issue by dcotelessa** [dcotelessa/cssbattle-solutions#37]
### Date

Jun 18, 2025

### CSS Solution(s)

```css
<style>&{background:#FADE8B}*{border:solid#D24444;border-width:40 var(--t,40 40)0;margin:40 145;*{margin:50 0;--t:0
```

### Comparison Images

<img width="858" alt="Image" src="https://github.com/user-attachments/assets/dca39f41-003d-49ff-9018-f99cbb06b340" />

### Additional Notes (Optional)

Three is a magic number.

### Confirmation

- [x] I have tested my CSS solution and it renders correctly
- [x] My CSS code blocks are properly formatted with opening and closing backticks
- [x] The comparison images (if any) clearly show the target vs my result
