### ISSUE TITLE
[CSSBattle] Daily Target - Jun 21, 2025

### ISSUE THREAD

**Issue by dcotelessa** [dcotelessa/cssbattle-solutions#40]
### Date

Jun 21, 2025

### CSS Solution(s)

```css
<p><p><p><p><p><p><style>&{background:#6592CF}p{border:80px solid#0000;border-top-color:var(--t,#F7CB71);width:0;margin:var(--m,150 92);+p{--m:-350 132;+p{scale:-1;--m:70 92;+p{--m:-190 132;+p{--t:#fff;scale:.25;--m:90 52;+p{scale:-.25;--m:-290 52
```

### Comparison Images

<img width="857" alt="Image" src="https://github.com/user-attachments/assets/9ffac7be-9f4c-441a-a26a-57ddc8d8ba35" />

### Additional Notes (Optional)

Fish.

### Confirmation

- [x] I have tested my CSS solution and it renders correctly
- [x] My CSS code blocks are properly formatted with opening and closing backticks
- [x] The comparison images (if any) clearly show the target vs my result
