### ISSUE TITLE
[CSSBattle] Daily Target - Jun 27, 202

### ISSUE THREAD

**Issue by dcotelessa** [dcotelessa/cssbattle-solutions#48]
### Date

Jun 27, 202

### CSS Solution(s)

```css
<p><p a><p><style>*{background:#394257}p{border:solid#D24444;border-width:40 0 0 40;padding:40;margin:20 192-60 72}[a]{scale:-1 1;margin-left:192
```

### Comparison Images

<img width="858" alt="Image" src="https://github.com/user-attachments/assets/744086ff-33f2-48d1-8081-dc0a013bdee1" />

### Additional Notes (Optional)

Corners.

### Confirmation

- [x] I have tested my CSS solution and it renders correctly
- [x] My CSS code blocks are properly formatted with opening and closing backticks
- [x] The comparison images (if any) clearly show the target vs my result
