### ISSUE TITLE
[CSSBattle] Daily Target - Jun 29, 2025

### ISSUE THREAD

**Issue by dcotelessa** [dcotelessa/cssbattle-solutions#51]
### Date

Jun 29, 2025

### CSS Solution(s)

```css
<p><style>*{background:conic-gradient(#48BF7D 25%,#FADE8B 0 50%,#D24444 0 75%,#394257 0)}p{border-top:5em
dotted#fff;margin:110 22;clip-path:polygon(0 50%,25%50%,50%-9%,75%50%,100%50%,99%100%,0 100%
```

### Comparison Images

<img width="857" alt="Image" src="https://github.com/user-attachments/assets/8ed5a59a-9bc2-4ea2-8096-6ae9f0b29655" />

### Additional Notes (Optional)

Kaleidoscope.

### Confirmation

- [x] I have tested my CSS solution and it renders correctly
- [x] My CSS code blocks are properly formatted with opening and closing backticks
- [x] The comparison images (if any) clearly show the target vs my result
