### ISSUE TITLE
[CSSBattle] Daily Target - Jun 5, 2025

### ISSUE THREAD

**Issue by dcotelessa** [dcotelessa/cssbattle-solutions#8]
### Date

Jun 5, 2025

### CSS Solution(s)

```css
<p><p a><p b><style>[a],*{background:#394257}body{display:flex;margin:14 0}p{background:radial-gradient(1q at 50vw 50vw,#0000 130px,#EED9D9 0 170px,#0000 0);border:solid#EED9D9;width:110;border-width:0 40 40 0}[a]{width:100;border-width:40 0}[b]{scale:-1 1
```

### Comparison Images

<img width="856" alt="Image" src="https://github.com/user-attachments/assets/6fbc0f10-68dd-4443-91c5-3bd11e1c635e" />

### Confirmation

- [x] I have tested my CSS solution
- [x] The comparison images show the target vs my result
