### ISSUE TITLE
[CSSBattle] Daily Target - Jun 6, 2025

### ISSUE THREAD

**Issue by dcotelessa** [dcotelessa/cssbattle-solutions#9]
### Date

Jun 6, 2025

### CSS Solution(s)

```css
<p><p><style>*{background:var(--b,#2D3464)}body{margin:45 95;padding:100;--b:radial-gradient(#C0D6E7 25px,#0000 0);background-size:70px 70px}p{color:D95362;padding:25;margin:-20;box-shadow:0 70px,70px 0,30vw 0,40vw 0,45vw 0;+p{scale:-1;margin:-50-20
```

### Comparison Images

<img width="855" alt="Image" src="https://github.com/user-attachments/assets/a9e7788e-14d6-44e2-882c-7874d277abb0" />

### Additional Notes (Optional)

Dots and Squares, and a line.

### Confirmation

- [x] I have tested my CSS solution
- [x] The comparison images show the target vs my result
